const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>'NT$ '+Number(n).toLocaleString('zh-TW');
let session,products=[],settings={},category='noodle',cart=[],quote=null,current=null,editIndex=-1,sending=false,receipt=null;
try{cart=JSON.parse(sessionStorage.getItem('cj-cart-v2')||'[]');if(!Array.isArray(cart))cart=[]}catch{cart=[]}
const seasons=['胡椒粉','烏醋','香油','蒜泥','香菜'], spices=['不辣','微辣','小辣','中辣','大辣'];
let staticDemo=false; async function api(path,data){try{const r=await fetch(path,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json','X-CSRF-Token':session?.csrf||''}:{},body:data?JSON.stringify(data):undefined});const j=await r.json();if(!r.ok)throw Error(j.error||'暫時無法連線');return j}catch(e){if(!staticDemo)throw e;if(path==='/api/session')return {csrf:'static-demo',demo:true,logged_in:false,admin:false,liff_id:''};if(path==='/api/catalog')return {settings:{name:'川記麵線糊',address:'807高雄市三民區達德里熱河一街355號',lead_minutes:15,max_days:7,accepting:true},products:[{id:'n0',name:'四喜麵線糊',category:'noodle',small:95,large:110,ingredients:['大腸','蚵仔','蝦仁','發魷魚'],active:true},{id:'n1',name:'經典麵線糊',category:'noodle',small:80,large:95,ingredients:['大腸','蚵仔','虱目魚漿'],active:true},{id:'n2',name:'大腸麵線糊',category:'noodle',small:70,large:85,ingredients:['大腸','虱目魚漿','貢丸'],active:true},{id:'n3',name:'蚵仔麵線糊',category:'noodle',small:70,large:85,ingredients:['蚵仔','虱目魚漿','貢丸'],active:true},{id:'n4',name:'蝦仁麵線糊',category:'noodle',small:70,large:85,ingredients:['蝦仁','虱目魚漿','貢丸'],active:true},{id:'n5',name:'魷魚麵線糊',category:'noodle',small:70,large:85,ingredients:['發魷魚','虱目魚漿','貢丸'],active:true},{id:'n6',name:'清麵線糊',category:'noodle',small:40,large:50,ingredients:['油條','麵線糊'],active:true},{id:'s0',name:'滷板豆腐（4塊）',category:'side',price:20,ingredients:[],active:true},{id:'s1',name:'滷米血（6塊）',category:'side',price:20,ingredients:[],active:true},{id:'s2',name:'滷豆乾（6塊）',category:'side',price:20,ingredients:[],active:true},{id:'s3',name:'滷貢丸（3顆）',category:'side',price:15,ingredients:[],active:true},{id:'s4',name:'滷蛋（1顆）',category:'side',price:15,ingredients:[],active:true},{id:'a0',name:'大腸',category:'addon',price:20,ingredients:[],active:true},{id:'a1',name:'鮮蚵',category:'addon',price:20,ingredients:[],active:true},{id:'a2',name:'蝦仁',category:'addon',price:20,ingredients:[],active:true},{id:'a3',name:'魷魚',category:'addon',price:20,ingredients:[],active:true},{id:'a4',name:'虱目魚漿',category:'addon',price:15,ingredients:[],active:true},{id:'a5',name:'油條',category:'addon',price:15,ingredients:[],active:true},{id:'a6',name:'貢丸',category:'addon',price:15,ingredients:[],active:true}]};if(path==='/api/quote')return {total:(data.items||[]).reduce((s,i)=>{const p=products.find(x=>x.id===i.product_id);return s+(p?.category==='noodle'?(p?.[i.size]||0):p?.price||0)*(i.qty||1)},0),items:data.items};if(path==='/api/orders')return {id:'試用訂單',demo:true,items:(data.items||[]).map(i=>{const p=products.find(x=>x.id===i.product_id)||{};return {...i,name:p.name||'餐點',category:p.category||'noodle',subtotal:(p.category==='noodle'?(p[i.size]||0):p.price||0)*(i.qty||1),extras:[],omit:i.omit||[],spicy:i.spicy||'不辣',basil:!!i.basil}}),total:data.expected_total,name:data.name,phone:data.phone,pickup:data.pickup,note:data.note,payment_status:'unpaid',notifications:[]};throw e}}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),3500)}
function persist(){sessionStorage.setItem('cj-cart-v2',JSON.stringify(cart));sessionStorage.removeItem('cj-order-attempt');quote=null}
function getProduct(id){return products.find(p=>p.id===id)}
function unit(i){const p=getProduct(i.product_id);if(!p)return 0;return p.category==='noodle'?p[i.size]+Object.entries(i.extras||{}).reduce((n,[id,q])=>n+(getProduct(id)?.price||0)*q,0):p.price*(i.qty||1)}
function total(){return cart.reduce((s,i)=>s+unit(i),0)}
function photo(p){return p.photo?`<img class="food-photo" src="/media/${esc(p.photo)}" alt="${esc(p.name)}">`:`<div class="food-placeholder" aria-hidden="true"><span>川記</span><small>${p.category==='side'?'滷味':'麵線糊'}</small></div>`}
function header(title='',back=false){return `<header class="shop-header">${back?'<button class="icon-button" data-nav="" aria-label="返回菜單">‹</button>':'<span class="wordmark">川記</span>'}<div><strong>${esc(title||settings.name)}</strong><small>${back?'每一份，照你的喜好':'線上點餐 · 到店自取'}</small></div><button class="text-button" data-nav="orders">我的訂單</button></header>${session.demo?'<div class="demo-strip">操作試用版 · 不會發送 LINE 訊息或收款</div>':''}`}
function shell(html){$('#app').innerHTML=html;document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>nav(b.dataset.nav))}
function nav(page){if(location.hash.slice(1)===page)route();else location.hash=page}
function summaryLine(i){return [i.spicy||'不辣',i.omit?.length?'不加'+i.omit.join('、'):'正常調味',i.basil?'香菜換九層塔':'',...Object.entries(i.extras||{}).filter(([,q])=>q).map(([id,q])=>(getProduct(id)?.name||'已下架加料')+'×'+q)].filter(Boolean).join(' · ')}
function menu(){
 const items=products.filter(p=>p.category===category);
 shell(header()+`<main class="shop-main"><section class="store-banner"><span class="mini-label">現點現做 · 暖心上桌</span><h1>今天，想吃哪一碗？</h1><p>11:00–23:00・週六公休</p><div class="address">${esc(settings.address||'取餐地址待店家設定')}</div></section>${!settings.accepting?'<div class="warning">目前暫停接單，歡迎稍後再來。</div>':''}<nav class="category-tabs" aria-label="餐點分類"><button data-cat="noodle" class="${category==='noodle'?'active':''}">招牌麵線</button><button data-cat="side" class="${category==='side'?'active':''}">加點滷味</button></nav><div class="section-heading"><h2>${category==='noodle'?'每一碗，都能客製':'配一份，剛剛好'}</h2><span>${items.length} 道餐點</span></div><div class="product-list">${items.map(p=>`<button class="product-row" data-product="${esc(p.id)}">${photo(p)}<span class="product-info"><strong>${esc(p.name)}</strong><span>${esc(p.ingredients.join('、')||p.description||'現滷好滋味')}</span><b>${money(p.category==='noodle'?p.small:p.price)}${p.category==='noodle'?'<small> 起</small>':''}</b></span><span class="add-circle" aria-label="選餐">＋</span></button>`).join('')||'<div class="empty-state">目前沒有上架餐點</div>'}</div><p class="small-print">${settings.lead_minutes} 分鐘前預訂 · 可預訂 ${settings.max_days} 天內餐點<br>各碗可分別設定調味；如有過敏或特殊需求，請聯繫店家確認。</p></main><div class="bottom-bar"><button class="primary full" id="cart-button"><span>購物車 <b class="count">${cart.reduce((s,i)=>s+(i.qty||1),0)}</b></span><span>${money(total())}　查看 ›</span></button></div>`);
 document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{category=b.dataset.cat;menu()});document.querySelectorAll('[data-product]').forEach(b=>b.onclick=()=>openItem(b.dataset.product));$('#cart-button').onclick=()=>nav('cart');
}
function openItem(id,index=-1){const p=getProduct(id);if(!p)return toast('這項餐點已下架，請移除後重新選擇');editIndex=index;current=index>=0?structuredClone(cart[index]):{product_id:id,size:'small',extras:{},omit:[],spicy:'不辣',basil:false,qty:1};renderItem();$('#item-dialog').showModal()}
function renderItem(){const p=getProduct(current.product_id), noodle=p.category==='noodle';
 $('#item-dialog').innerHTML=`<div class="sheet-head"><div><small>${editIndex<0?'加入一份餐點':'修改這一份'}</small><h2>${esc(p.name)}</h2></div><button class="icon-button" id="close-item" aria-label="關閉餐點設定">×</button></div><div class="sheet-body"><p class="muted">${esc(p.ingredients.join('、')||p.description)}</p>${noodle?`<fieldset><legend>選擇大小 <span>必選</span></legend><div class="option-grid">${[['small','小碗',p.small],['large','大碗',p.large]].map(([v,l,n])=>`<label class="choice"><input type="radio" name="size" value="${v}" ${current.size===v?'checked':''}><span>${l}<b>${money(n)}</b></span></label>`).join('')}</div></fieldset><fieldset><legend>加料 <span>選填・每碗最多 6 份</span></legend>${products.filter(x=>x.category==='addon').map(a=>`<div class="addon-row"><span>${esc(a.name)} <small>＋$${a.price}</small></span><div class="stepper"><button data-minus="${a.id}" aria-label="減少${esc(a.name)}">−</button><output>${current.extras[a.id]||0}</output><button data-plus="${a.id}" aria-label="增加${esc(a.name)}">＋</button></div></div>`).join('')}</fieldset><fieldset><legend>辣度 <span>預設不辣</span></legend><div class="chips">${spices.map(v=>`<label class="chip"><input type="radio" name="spicy" value="${v}" ${current.spicy===v?'checked':''}><span>${v}</span></label>`).join('')}</div></fieldset><fieldset><legend>不加什麼？ <span>勾選「不要」的項目</span></legend><div class="check-grid">${[...new Set([...seasons,...p.ingredients])].map(v=>`<label class="check"><input type="checkbox" name="omit" value="${esc(v)}" ${current.omit.includes(v)?'checked':''}><span>不加${esc(v)}</span></label>`).join('')}</div><label class="basil"><input type="checkbox" id="basil" ${current.basil?'checked':''}><span>香菜換九層塔<small>選擇後會自動不加香菜</small></span></label></fieldset>`:`<fieldset><legend>要幾份？</legend><div class="addon-row"><span>每份 ${money(p.price)}</span><div class="stepper"><button id="side-minus" aria-label="減少份數">−</button><output>${current.qty}</output><button id="side-plus" aria-label="增加份數">＋</button></div></div></fieldset>`}</div><div class="sheet-foot"><button class="primary full" id="save-item"><span>${editIndex>=0?'儲存這一份':noodle?'加入這一碗':'加入購物車'}</span><b>${money(unit(current))}</b></button></div>`;
 $('#close-item').onclick=()=>$('#item-dialog').close();
 document.querySelectorAll('#item-dialog input').forEach(el=>el.onchange=()=>{if(el.name==='size')current.size=el.value;if(el.name==='spicy')current.spicy=el.value;if(el.name==='omit'){current.omit=[...document.querySelectorAll('[name="omit"]:checked')].map(x=>x.value);if(!current.omit.includes('香菜'))current.basil=false}if(el.id==='basil'){current.basil=el.checked;current.omit=current.omit.filter(x=>x!=='香菜');if(el.checked)current.omit.push('香菜')}const scroll=$('#item-dialog .sheet-body').scrollTop;renderItem();$('#item-dialog .sheet-body').scrollTop=scroll});
 function adjust(id,delta){const sum=Object.values(current.extras).reduce((a,b)=>a+b,0);if(delta>0&&sum>=6)return toast('每碗最多加料6份');current.extras[id]=Math.max(0,(current.extras[id]||0)+delta);const scroll=$('#item-dialog .sheet-body').scrollTop;renderItem();$('#item-dialog .sheet-body').scrollTop=scroll}
 document.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>adjust(b.dataset.plus,1));document.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>adjust(b.dataset.minus,-1));
 if(!noodle){$('#side-minus').onclick=()=>{current.qty=Math.max(1,current.qty-1);renderItem()};$('#side-plus').onclick=()=>{current.qty=Math.min(20,current.qty+1);renderItem()}}
 $('#save-item').onclick=()=>{if(editIndex<0){if(cart.length>=40)return toast('一筆訂單最多40項');cart.push(current)}else cart[editIndex]=current;persist();$('#item-dialog').close();toast('已儲存，口味會套用這一份');route()};
}
async function cartPage(){
 shell(header('確認你的餐點',true)+`<main class="shop-main"><div class="page-title"><h1>購物車</h1><p>每一碗分開設定，製餐時更清楚。</p></div><div id="cart-lines">${cart.map((i,n)=>{const p=getProduct(i.product_id);return `<article class="cart-card"><div class="cart-line"><span class="bowl-tag">第 ${n+1} 份</span><strong>${esc(p?.name||'已下架餐點')} ${p?.category==='noodle'?(i.size==='large'?'大碗':'小碗'):'×'+i.qty}</strong><b>${money(unit(i))}</b></div><p>${p?.category==='noodle'?esc(summaryLine(i)):'固定份量滷味'}</p><div class="cart-actions"><button data-edit="${n}">修改</button><button data-copy="${n}">再來一份</button><button data-remove="${n}" class="danger-text">移除</button></div></article>`}).join('')||'<div class="empty-state"><h2>先挑一碗喜歡的吧</h2><p>你的餐點會出現在這裡。</p><button class="primary" data-nav="">前往菜單</button></div>'}</div>${cart.length?`<button class="secondary full" data-nav="">＋ 繼續加點</button><div class="total-row"><span>餐點總額</span><strong id="quote-total">${money(total())}</strong></div><p class="form-error" id="quote-error" role="alert"></p>`:''}</main>${cart.length?'<div class="bottom-bar"><button class="primary full" id="checkout" disabled><span>確認餐點，下一步</span><span>›</span></button></div>':''}`);
 document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openItem(cart[+b.dataset.edit].product_id,+b.dataset.edit));document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>{if(cart.length>=40)return toast('一筆最多40項');cart.splice(+b.dataset.copy+1,0,structuredClone(cart[+b.dataset.copy]));persist();cartPage()});document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{cart.splice(+b.dataset.remove,1);persist();cartPage()});
 if(cart.length){try{quote=await api('/api/quote',{items:cart});if(!$('#checkout'))return;$('#quote-total').textContent=money(quote.total);$('#checkout').disabled=false;$('#checkout').onclick=()=>nav('checkout')}catch(e){if($('#quote-error'))$('#quote-error').textContent=e.message}}
}
function localDate(d){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).format(d)}
function dateOptions(){const options=[];for(let k=0;k<=settings.max_days;k++){const d=new Date(Date.now()+k*86400000),date=localDate(d),weekday=new Date(date+'T12:00:00+08:00').getUTCDay();if(weekday===6)continue;options.push({value:date,label:(k===0?'今天':k===1?'明天':date.slice(5).replace('-','/'))+'（'+['日','一','二','三','四','五','六'][weekday]+'）'})}return options}
function checkoutPage(){if(!cart.length)return nav('cart');
 shell(header('填寫取餐資料',true)+`<main class="shop-main"><div class="page-title"><h1>就差最後一步</h1><p>選好取餐時間，留下聯絡資料。</p></div><form id="checkout-form"><section class="form-card"><h2>01　取餐資訊</h2><div class="location-box"><strong>到店自取</strong><p>${esc(settings.address||'請聯絡店家確認地址')}</p></div><label class="field">取餐日期<select id="pickup-date" required>${dateOptions().map(d=>`<option value="${d.value}">${d.label}</option>`).join('')}</select></label><label class="field">取餐時間<select id="pickup-time" required></select></label><p class="help">至少提前 ${settings.lead_minutes} 分鐘 · 週六公休</p></section><section class="form-card"><h2>02　基本資料</h2><label class="field">取餐姓名<input id="customer-name" autocomplete="name" maxlength="30" placeholder="怎麼稱呼你？" required></label><label class="field">手機號碼<input id="customer-phone" type="tel" autocomplete="tel" inputmode="tel" maxlength="10" pattern="09[0-9]{8}" placeholder="09xxxxxxxx" required></label><label class="field">訂單備註 <span>選填</span><textarea id="customer-note" maxlength="200" rows="3" placeholder="其他需求請寫在這裡，由店家確認"></textarea></label></section><section class="form-card"><h2>03　付款方式</h2><label class="payment-option selected"><input type="radio" name="payment" value="cash" checked><span><strong>現場付款</strong><small>取餐時付款給店家</small></span><b>現金</b></label><label class="payment-option disabled"><input type="radio" name="payment" value="online" disabled><span><strong>線上付款</strong><small>LINE Pay 串接完成後開放</small></span><b>尚未開通</b></label></section><div class="checkout-summary"><span>共 ${cart.reduce((a,i)=>a+(i.qty||1),0)} 份餐點</span><strong>${money(quote?.total??total())}</strong></div><p class="help">資料僅用於訂單與取餐聯繫。<br>送出後，訂單會登記於店家後台${session.demo?'；本次為測試，不會發送 LINE 訊息':'，並由官方 LINE 發送確認訊息'}。</p><p id="checkout-error" class="form-error" role="alert"></p><div class="bottom-bar"><button class="primary full" id="place-order" type="submit"><span>${session.demo?'送出測試訂單':'確認並送出訂單'}</span><b>${money(quote?.total??total())}</b></button></div></form></main>`);
 function times(){const date=$('#pickup-date').value;let html='';for(let h=11;h<23;h++)for(let m=0;m<60;m+=15){const t=String(h).padStart(2,'0')+':'+String(m).padStart(2,'0');if(new Date(date+'T'+t+':00+08:00').getTime()>=Date.now()+settings.lead_minutes*60000)html+=`<option value="${t}">${t}</option>`}$('#pickup-time').innerHTML=html||'<option value="">當天已無可預訂時段，請選其他日期</option>'}
 $('#pickup-date').onchange=times;times();$('#checkout-form').onsubmit=async e=>{e.preventDefault();if(sending)return;sending=true;$('#place-order').disabled=true;$('#checkout-error').textContent='';
 try{let key=sessionStorage.getItem('cj-order-attempt');if(!key){key=crypto.randomUUID();sessionStorage.setItem('cj-order-attempt',key)}receipt=await api('/api/orders',{idempotency_key:key,items:cart,expected_total:quote?.total??total(),name:$('#customer-name').value,phone:$('#customer-phone').value,pickup:$('#pickup-date').value+' '+$('#pickup-time').value,note:$('#customer-note').value,payment_method:'cash'});cart=[];persist();sessionStorage.setItem('cj-last-order',receipt.id);nav('success')}
 catch(error){$('#checkout-error').textContent=error.message;if(error.message.includes('價格')){const c=await api('/api/catalog');products=c.products;quote=null;$('#checkout-error').append(document.createTextNode(' 請返回購物車核對新價格。'))}}
 finally{sending=false;if($('#place-order'))$('#place-order').disabled=false}};
}
function orderItems(o){return o.items.map((i,n)=>`<div class="receipt-item"><strong>${n+1}. ${esc(i.name)} ${i.size?(i.size==='large'?'大碗':'小碗'):'×'+i.qty}<span>${money(i.subtotal)}</span></strong>${i.category==='noodle'?`<p>${esc([i.spicy,'不加：'+(i.omit.join('、')||'無'),'加料：'+(i.extras.map(e=>e.name+'×'+e.qty).join('、')||'無'),i.basil?'香菜換九層塔':''].filter(Boolean).join(' · '))}</p>`:''}</div>`).join('')}
async function successPage(){
 try{if(!receipt){const id=sessionStorage.getItem('cj-last-order');if(!id)return nav('orders');receipt=await api('/api/order/'+encodeURIComponent(id))}
 const o=receipt;const sent=o.notifications?.find(n=>n.recipient==='客人');
 shell(header('訂單確認',true)+`<main class="shop-main"><div class="success-title"><div class="success-icon">✓</div><h1>${o.demo?'測試下單完成':'下單完成'}</h1><p>訂單已登記，店家將依序安排製作。</p><b class="order-code">${esc(o.id)}</b></div><div class="confirmation-note">${o.demo?'試用版：以下是官方 LINE 確認訊息的內容預覽，尚未實際發送。':sent?.state==='sent'?'官方 LINE 已發送下單確認訊息。':sent?.state==='failed'?'訂單已成立，但 LINE 通知尚未送達。請保留訂單編號。':'訂單已成立，LINE 確認訊息正在排程傳送。'}</div><article class="receipt"><h2>${esc(settings.name)}</h2><div class="receipt-key"><span>取餐時間</span><strong>${esc(o.pickup)}</strong></div><div class="receipt-key"><span>取餐人</span><strong>${esc(o.name)} · ${esc(o.phone)}</strong></div>${orderItems(o)}<div class="total-row"><span>總金額</span><strong>${money(o.total)}</strong></div><div class="payment-badge">現場付款 · ${o.payment_status==='paid'?'已付款':'尚未付款'}</div>${o.note?`<p>備註：${esc(o.note)}</p>`:''}<p class="help">${esc(settings.address)}${settings.phone?'<br>電話：'+esc(settings.phone):''}</p></article><button class="secondary full" data-nav="">再點一筆</button><p class="small-print">修改或取消訂單，請聯繫店家。</p></main>`)
 }catch(e){toast(e.message);nav('orders')}
}
async function ordersPage(){shell(header('我的訂單',true)+'<main class="shop-main"><div class="page-title"><h1>我的訂單</h1></div><div id="history" class="muted">載入中…</div></main>');try{const data=await api('/api/my-orders');if(!$('#history'))return;$('#history').innerHTML=data.orders.map(o=>`<button class="history-card" data-id="${esc(o.id)}"><span>${esc(o.id)}<b>${({new:'新訂單',preparing:'製作中',ready:'可取餐',completed:'已完成',cancelled:'已取消'})[o.status]}</b></span><strong>${esc(o.pickup)}</strong><span>${o.items.length} 項餐點 · ${money(o.total)}<small>查看明細 ›</small></span></button>`).join('')||'<div class="empty-state">還沒有訂單，從菜單挑選喜歡的餐點吧。</div>';document.querySelectorAll('[data-id]').forEach(b=>b.onclick=async()=>{receipt=await api('/api/order/'+b.dataset.id);nav('success')})}catch(e){if($('#history'))$('#history').textContent=e.message}}
function route(){const page=location.hash.slice(1);if(page==='cart')cartPage();else if(page==='checkout')checkoutPage();else if(page==='success')successPage();else if(page==='orders')ordersPage();else menu();window.scrollTo(0,0)}
async function init(){try{staticDemo=location.hostname.endsWith('.chatgpt.site');session=await api('/api/session');const data=await api('/api/catalog');products=data.products;settings=data.settings;if(!session.demo){await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://static.line-scdn.net/liff/edge/2/sdk.js';s.onload=resolve;s.onerror=reject;document.head.append(s)});await liff.init({liffId:session.liff_id});if(!liff.isLoggedIn()){liff.login();return}await api('/api/auth/line',{id_token:liff.getIDToken()})}window.addEventListener('hashchange',route);route()}catch(e){$('#app').innerHTML='<div class="empty-state"><h1>暫時無法開啟點餐</h1><p>'+esc(e.message||'請稍後再試')+'</p><button class="primary" id="reload">重新載入</button></div>';$('#reload').onclick=()=>location.reload()}}
init();




